{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "preamp.fullname" . }}
  labels:
    {{- include "preamp.labels" . | nindent 4 }}
type: Opaque
stringData:
  PREAMP_ENCRYPTION_KEY: {{ required "secrets.encryptionKey is required when not using existingSecret" .Values.secrets.encryptionKey | quote }}
  {{- if .Values.ui.enabled }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ required "secrets.oidcClientSecret is required when ui.enabled" .Values.secrets.oidcClientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ required "secrets.oauthCookieSecret is required when ui.enabled" .Values.secrets.oauthCookieSecret | quote }}
  {{- else }}
  PREAMP_DEV_USERNAME: {{ required "devCredentials.username is required when ui.enabled=false" .Values.devCredentials.username | quote }}
  PREAMP_DEV_PASSWORD: {{ required "devCredentials.password is required when ui.enabled=false" .Values.devCredentials.password | quote }}
  {{- end }}
{{- end }}
